export const types = {
  LOGIN_USER: "[AUTH] LOGIN_USER",
  LOGOUT_USER: "[AUTH] LOGOUT_USER",

  SET_ROLES: "[ROLES] SET_ROLES",
  CREATE_ROLE: "[ROLES] CREATE_ROLE",
  UPDATE_ROLE: "[ROLES] UPDATE_ROLE",
  DELETE_ROLE: "[ROLES] DELETE_ROLE",

  SET_BRANDS: "[ROLES] SET_BRANDS",
  CREATE_BRAND: "[ROLES] CREATE_BRAND",
  UPDATE_BRAND: "[ROLES] UPDATE_BRAND",
  DELETE_BRAND: "[ROLES] DELETE_BRAND",

  SET_COLORS: "[ROLES] SET_COLORS",
  CREATE_COLOR: "[ROLES] CREATE_COLOR",
  UPDATE_COLOR: "[ROLES] UPDATE_COLOR",
  DELETE_COLOR: "[ROLES] DELETE_COLOR",

  SET_MODELS: "[ROLES] SET_MODELS",
  CREATE_MODEL: "[ROLES] CREATE_MODEL",
  UPDATE_MODEL: "[ROLES] UPDATE_MODEL",
  DELETE_MODEL: "[ROLES] DELETE_MODEL",

  SET_SIZES: "[ROLES] SET_SIZES",
  CREATE_SIZE: "[ROLES] CREATE_SIZE",
  UPDATE_SIZE: "[ROLES] UPDATE_SIZE",
  DELETE_SIZE: "[ROLES] DELETE_SIZE",

  SET_PRODUCTS: "[ROLES] SET_PRODUCTS",
  CREATE_PRODUCT: "[ROLES] CREATE_PRODUCT",
  UPDATE_PRODUCT: "[ROLES] UPDATE_PRODUCT",
  DELETE_PRODUCT: "[ROLES] DELETE_PRODUCT",

  SET_USERS: "[ROLES] SET_USERS",
  CREATE_USER: "[ROLES] CREATE_USER",
  UPDATE_USER: "[ROLES] UPDATE_USER",
  DELETE_USER: "[ROLES] DELETE_USER",
};
